version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notesdb_prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: 
      context:
        ./frontend
    ports:
      - "3000:3000"

  backend:
    build: 
      context:
        ./backend
    environment:
      - NODE_ENV=production
    ports:
      - "3333:3333"

volumes:
  postgres_data:

networks:
  default:
    name: corenotes
